remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Exploring 3D-aware Latent Spaces <br> for Efficiently Learning Numerous Scenes"
description: "Antoine Schnepf <sup>*</sup>, Karim Kassab<sup>*</sup>, Jean-Yves Franceschi, Laurent Caraffa, <br> Flavian Vasile, Jeremie Mary, Andrew Comport, Valérie Gouet-Brunet<br><sup>*</sup> Equal contributions"

show_downloads: True
